brew "bat"
brew "curl"
brew "diff-so-fancy"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "node"
brew "gemini-cli"
brew "gh"
brew "git"
brew "htop"
brew "imagemagick"
brew "jq"
brew "mas"
brew "ncdu"
brew "nvm"
brew "ollama"
brew "pandoc"
brew "poppler"
brew "python@3.14"
brew "rbenv"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "wget"
brew "zoxide"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "affinity"
cask "astropad"
cask "claude"
cask "claude-code"
cask "discord"
cask "font-jetbrains-mono"
cask "gplates"
cask "grammarly-desktop"
cask "helium-browser"
cask "iterm2"
cask "itermai"
cask "logi-options+"
cask "obsidian"
cask "protonvpn"
cask "skim"
cask "steam"
cask "vlc"
cask "zed"
mas "1Password for Safari", id: 1569813296
mas "Fresco", id: 1251572132
mas "Goodnotes", id: 1444383602
mas "Highlights", id: 1498912833
mas "iA Writer", id: 775737590
